[package]
name = "inertia-api-services"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inertia-api-domain = { path = "../inertia-api-domain" }
scylla = { version = "0.13.0", features = ["time"] }
