version: "3.8"

services:
  api:
    depends_on:
      - db
      - redis
    hostname: api
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - internal
    ports:
      - 3001:3001
    deploy:
      restart_policy:
        condition: on-failure
    links:
      - "db:db"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/inertia?sslmode=disable
      - REDIS_URL=redis://redis:6379
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inertia
    ports:
      - 5432:5432
    networks:
      - internal
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: postgres -c max_connections=300
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - internal
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

volumes:
  postgres-data:
  redis-data:

networks:
  internal:
    driver: bridge
