# fly.toml app configuration file generated for inertia-devel on 2024-02-01T20:00:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'inertia-devel'
primary_region = 'waw'

kill_signal = "SIGINT"
kill_timeout = 5

[processes]
api = "/bin/app api"
worker = "/bin/app worker"

[build]

[[services]]
internal_port = 3001
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ['api']
http_checks = []
[[services.ports]]
handlers = ['http']
port = 80
force_https = true
[[services.ports]]
handlers = ['http', 'tls']
port = 443

[[services]]
processes = ['worker']
min_machines_running = 1
auto_start_machines = true
auto_stop_machines = true
[[services.ports]]
port = 3001


[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024
processes = ['api']

[[vm]]
cpu_kind = 'shared'
cpus = 1
memory_mb = 512
processes = ['worker']
